#Defines command suggestions visible by whitelist for the default group
visible-commands:
    - tpahere
    - tpaccept
    - tpacancel
    - sethome
    - home
    - warp
    - spawn
    - rules
    - help
    - tips
    - vote
    - tell
    - msg
    - me
    - afk
    - suicide

#Defines command suggestions that should not be visible by anyone (by blacklist)
#by default, this overrides visible-commands and group visibility
invisible-commands:
    - execute
    - testfor
    - particle

#defines groups that have differing command whitelists and blacklists
#give group permission with "aztectabcompleter.group.group-name-here"
#all applicable groups to a user will be checked for blacklist and whitelist matches if enabled in filter-order
#note: groups only have visible and invisible command lists, they do not have their own filter-order or default action.
#if you want a user to have multiple group's commands, give them the permission for each
groups:
    chatmod:
        visible-commands:
            - nick
            - kick
            - mute
            - seen
        invisible-commands:
            - something
    moderator:
        visible-commands:
            - gms
            - gmsp
            - tp
        invisible-commands:
            - somethingelse


#defines the order used to filter commands, each filtering method is subtractive from the last
#valid filtering mods:
#   whitelist: allows any command that appears in 'visible-commands', skips other filtering if matched
#   blacklist: denies any command that appears in 'invisible-commands', skips other filtering if matched
#   group-whitelists: for each group the user has the "aztectabcompleter.group.group-name-here" permission for:
#                     process the 'visible-commands' for the group as described above
#   group-blacklists: for each group the user has the "aztectabcompleter.group.group-name-here" permission for:
#                     process the 'invisible-commands' for the group as described above
# default configuration:
#filter-order: [blacklist,group-blacklists,whitelist,group-whitelists]
filter-order: [blacklist,group-blacklists,whitelist,group-whitelists]

#default behavior when no filters match the command
#Default
#Possible values:
#   DENY_FINAL : deny the command from being suggested
#   ALLOW_FINAL: allow the command to be suggested
#filter-default: DENY_FINAL
filter-default: DENY_FINAL

#kick players who join before the plugin is fully enabled.
kick-early-joins: true
kick-message: Please wait a moment for the server to load!

#additional feature to also block command that is not suggested/whitelisted
block-commands: false
block-message: You are not allowed to use that command!

# use the following configuration to enable classic behavior:
#filter-order: [whitelist]
#filter-default: DENY_FINAL
#this will disable blacklists, groups, and make the default action to deny any non-matching entries.

