#Defines commands visible to all users
visible-commands:
    - tpahere
    - tpaccept
    - tpacancel
    - sethome
    - home
    - warp
    - spawn
    - rules
    - help
    - tips
    - vote
    - tell
    - msg
    - me
    - afk
    - suicide
    
